// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCOSrrm-Z8KnoTNvx4iVAai7BhC0Y0lgU',
    appId: '1:1055239765586:web:71fca8143586a7652da98b',
    messagingSenderId: '1055239765586',
    projectId: 'smarthome-6495e',
    authDomain: 'smarthome-6495e.firebaseapp.com',
    storageBucket: 'smarthome-6495e.appspot.com',
    measurementId: 'G-PBM4TPQSD1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHPAT6iqRxqssej_pOwWtEHfdFbv-WXtk',
    appId: '1:1055239765586:android:d7da282b97549a812da98b',
    messagingSenderId: '1055239765586',
    projectId: 'smarthome-6495e',
    storageBucket: 'smarthome-6495e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo5Y3EI1U-D8qpR6p03VZX-tuCWCZHFiE',
    appId: '1:1055239765586:ios:8196cfefcb12fff02da98b',
    messagingSenderId: '1055239765586',
    projectId: 'smarthome-6495e',
    storageBucket: 'smarthome-6495e.appspot.com',
    iosClientId: '1055239765586-lgeu4ot01cl7mrftfbo2eedi2vpebveh.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartHomeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo5Y3EI1U-D8qpR6p03VZX-tuCWCZHFiE',
    appId: '1:1055239765586:ios:8196cfefcb12fff02da98b',
    messagingSenderId: '1055239765586',
    projectId: 'smarthome-6495e',
    storageBucket: 'smarthome-6495e.appspot.com',
    iosClientId: '1055239765586-lgeu4ot01cl7mrftfbo2eedi2vpebveh.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartHomeApp',
  );
}
